//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    [Bind(Exclude = "Id")]
    public partial class Applied_Job
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [ScaffoldColumn(false)]
        public int Id { get; set; }
        public Nullable<System.DateTime> Applied_Date { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> FK_Candidate_id { get; set; }
        public Nullable<int> FK_Job_id { get; set; }
        public virtual Cadidate Cadidate { get; set; }
        public virtual Job Job { get; set; }
    }
}
