//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    [Bind(Exclude = "Id")]
    public partial class Candidates_Professional
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [ScaffoldColumn(false)]
        public int Id { get; set; }
        public string Company_Name { get; set; }
        public string Position { get; set; }
        public System.DateTime Experience_From { get; set; }
        public System.DateTime Experience_To { get; set; }
        public int FK_Candidate_id { get; set; }

        public virtual Candidate Candidate { get; set; }
    }
}
