//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Models
{
    using System;
    using System.Collections.Generic;
        using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;
    
    [Bind(Exclude = "Id")]
    public partial class Candidates_Education
    {[Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [ScaffoldColumn(false)]
        public int Id { get; set; }
        public string Course_Name { get; set; }
        public string Pasing_Year { get; set; }
        public string Total_Marks { get; set; }
        public string Obtained_Marks { get; set; }
        public string Division_CGPA { get; set; }
        public int FK_Candidate_id { get; set; }
    
        public virtual Candidate Candidate { get; set; }
    }
}
