//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    [Bind(Exclude = "Id")]
    public partial class Company
    {
        public Company()
        {
            this.Jobs = new HashSet<Job>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [ScaffoldColumn(false)]
        public int Id { get; set; }
        public string CEO { get; set; }
        public string Company_name { get; set; }
        public string Company_Contact { get; set; }
        public string Company_Email_id { get; set; }
        public string Company_Logo { get; set; }
        public string Company_Website { get; set; }
        public string Company_Fax { get; set; }
        public string Company_Description { get; set; }
        public string Company_Address { get; set; }
        public Nullable<bool> Company_Status_Ind { get; set; }

        public virtual ICollection<Job> Jobs { get; set; }
    }
}
